server:
  port: 9999

spring:
  datasource:
    username: root
    password: mysql1234
    url: jdbc:mysql://cdb-esm8w5qk.bj.tencentcdb.com:10059/oa
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5